/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Collaboration {
  'id' : CollaborationId,
  'title' : string,
  'campaign' : string,
  'publishedAt' : bigint,
  'quote' : string,
  'description' : string,
  'coverImage' : ExternalBlob,
  'celebrity' : string,
  'images' : Array<ExternalBlob>,
}
export type CollaborationId = bigint;
export interface Collection {
  'id' : CollectionId,
  'productIds' : Array<ProductId>,
  'name' : string,
  'description' : string,
  'coverImage' : ExternalBlob,
}
export type CollectionId = bigint;
export type ExternalBlob = Uint8Array;
export interface LookbookEntry {
  'id' : LookbookEntryId,
  'title' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'description' : string,
  'coverImage' : ExternalBlob,
  'images' : Array<ExternalBlob>,
}
export type LookbookEntryId = bigint;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'sizes' : Array<ProductSize>,
  'availability' : boolean,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'colors' : Array<ProductColor>,
  'price' : bigint,
  'material' : string,
  'images' : Array<ExternalBlob>,
}
export type ProductCategory = string;
export type ProductColor = string;
export interface ProductFilter {
  'color' : [] | [ProductColor],
  'size' : [] | [ProductSize],
  'maxPrice' : [] | [bigint],
  'category' : [] | [ProductCategory],
  'minPrice' : [] | [bigint],
}
export type ProductId = bigint;
export type ProductSize = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'filterProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getCollaborationById' : ActorMethod<[CollaborationId], [] | [Collaboration]>,
  'getCollaborations' : ActorMethod<[], Array<Collaboration>>,
  'getCollectionById' : ActorMethod<[CollectionId], [] | [Collection]>,
  'getCollections' : ActorMethod<[], Array<Collection>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getLookbookEntries' : ActorMethod<[], Array<LookbookEntry>>,
  'getLookbookEntryById' : ActorMethod<[LookbookEntryId], [] | [LookbookEntry]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCollection' : ActorMethod<[CollectionId], Array<Product>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];