/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductColor = IDL.Text;
export const ProductSize = IDL.Text;
export const ProductCategory = IDL.Text;
export const ProductFilter = IDL.Record({
  'color' : IDL.Opt(ProductColor),
  'size' : IDL.Opt(ProductSize),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(ProductCategory),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(ProductSize),
  'availability' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'colors' : IDL.Vec(ProductColor),
  'price' : IDL.Nat,
  'material' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const CollaborationId = IDL.Nat;
export const Collaboration = IDL.Record({
  'id' : CollaborationId,
  'title' : IDL.Text,
  'campaign' : IDL.Text,
  'publishedAt' : IDL.Int,
  'quote' : IDL.Text,
  'description' : IDL.Text,
  'coverImage' : ExternalBlob,
  'celebrity' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const CollectionId = IDL.Nat;
export const Collection = IDL.Record({
  'id' : CollectionId,
  'productIds' : IDL.Vec(ProductId),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'coverImage' : ExternalBlob,
});
export const LookbookEntryId = IDL.Nat;
export const LookbookEntry = IDL.Record({
  'id' : LookbookEntryId,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'description' : IDL.Text,
  'coverImage' : ExternalBlob,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'filterProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getCollaborationById' : IDL.Func(
      [CollaborationId],
      [IDL.Opt(Collaboration)],
      ['query'],
    ),
  'getCollaborations' : IDL.Func([], [IDL.Vec(Collaboration)], ['query']),
  'getCollectionById' : IDL.Func(
      [CollectionId],
      [IDL.Opt(Collection)],
      ['query'],
    ),
  'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getLookbookEntries' : IDL.Func([], [IDL.Vec(LookbookEntry)], ['query']),
  'getLookbookEntryById' : IDL.Func(
      [LookbookEntryId],
      [IDL.Opt(LookbookEntry)],
      ['query'],
    ),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCollection' : IDL.Func(
      [CollectionId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductColor = IDL.Text;
  const ProductSize = IDL.Text;
  const ProductCategory = IDL.Text;
  const ProductFilter = IDL.Record({
    'color' : IDL.Opt(ProductColor),
    'size' : IDL.Opt(ProductSize),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(ProductCategory),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(ProductSize),
    'availability' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'colors' : IDL.Vec(ProductColor),
    'price' : IDL.Nat,
    'material' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const CollaborationId = IDL.Nat;
  const Collaboration = IDL.Record({
    'id' : CollaborationId,
    'title' : IDL.Text,
    'campaign' : IDL.Text,
    'publishedAt' : IDL.Int,
    'quote' : IDL.Text,
    'description' : IDL.Text,
    'coverImage' : ExternalBlob,
    'celebrity' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const CollectionId = IDL.Nat;
  const Collection = IDL.Record({
    'id' : CollectionId,
    'productIds' : IDL.Vec(ProductId),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'coverImage' : ExternalBlob,
  });
  const LookbookEntryId = IDL.Nat;
  const LookbookEntry = IDL.Record({
    'id' : LookbookEntryId,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'description' : IDL.Text,
    'coverImage' : ExternalBlob,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'filterProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getCollaborationById' : IDL.Func(
        [CollaborationId],
        [IDL.Opt(Collaboration)],
        ['query'],
      ),
    'getCollaborations' : IDL.Func([], [IDL.Vec(Collaboration)], ['query']),
    'getCollectionById' : IDL.Func(
        [CollectionId],
        [IDL.Opt(Collection)],
        ['query'],
      ),
    'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getLookbookEntries' : IDL.Func([], [IDL.Vec(LookbookEntry)], ['query']),
    'getLookbookEntryById' : IDL.Func(
        [LookbookEntryId],
        [IDL.Opt(LookbookEntry)],
        ['query'],
      ),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCollection' : IDL.Func(
        [CollectionId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };